---
- name: Install tomcat
  become: yes
  hosts: appserver
  vars:
    - username: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false 
    - tomcat_version: 9.0.78
  tasks:
    - name: update apt repo and cache
      apt:
       update_cache: yes
       when: ansible_facts['os_family'] == "Debian"
    - name: install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        create_home: yes
        home: "{{ /opt/tomcat }}"
        name: "{{ username }}"
        shell: "{{ /bin/false }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"  
