---
- name: Install tomcat
  become: yes
  hosts: appserver
  tasks:
    - name: update apt repo and cache
      apt:
       update_cache: yes
      when: ansible_facts['os_family'] == "Debian"  
    - name: install apache 2 on ubuntu 
      ansible.builtin.apt: 
        name: apache 2 
        state: present 
      when: ansible_facts['os_family'] == "Debian" 