---
- name: Install lamp
  become: yes
  hosts: webserver
  tasks:
    - name: update ubuntu package
      apt:
        update_cache: yes 
      when: ansible_facts['os_family'] == "Debian"         
    - name: install apache2 on ubuntu
      ansible.builtin.package:
      package:
        name: "{{ apache_package }}"
        state: present 
      notify: 
        - ensure apache enabled and restarted 
    - name: install php on ubuntu 
      ansible.builtin.package:
      package: 
        name: "{{ item }}"
        state: present 
      loop: "{{ php_package }}"  
      notify: 
        - ensure apache enabled and restarted
    - name: copy the php info page
      ansible.builtin.copy:
        src: www/info.php
        dest: "{{ php_page_location }}"  
      notify: 
        - ensure apache enabled and restarted               
  handlers:          
    - name: ensure apache enabled and restarted
      ansible.builtin.service:
        name: "{{ apache_package }}" 
        enabled: yes
        state: restarted

